// Code generated by "go run err_generate.go"; DO NOT EDIT.

package sign

import (
	"errors"
	"fmt"
	"log/slog"

	"github.com/lanrat/dns/cmd/atomdns/internal/dnslog"
)

func (s *Sign) Err(err error) error { return fmt.Errorf("%s: %w", s.Key(), err) }

func (s *Sign) Errf(err string) error { return fmt.Errorf("%s: %w", s.Key(), errors.New(err)) }

func Err(err error) slog.Attr { return dnslog.Error(err) }

func (s *Sign) Key() string { return "sign" }

var log = func() *slog.Logger { return slog.Default().With("handler", "sign") }
