// Code generated by "go run err_generate.go"; DO NOT EDIT.

package id

import (
	"errors"
	"fmt"
	"log/slog"

	"github.com/lanrat/dns/cmd/atomdns/internal/dnslog"
)

func (i *Id) Err(err error) error { return fmt.Errorf("%s: %w", i.Key(), err) }

func (i *Id) Errf(err string) error { return fmt.Errorf("%s: %w", i.Key(), errors.New(err)) }

func Err(err error) slog.Attr { return dnslog.Error(err) }

func (i *Id) Key() string { return "id" }

var log = func() *slog.Logger { return slog.Default().With("handler", "id") }
