// Code generated by "go run err_generate.go"; DO NOT EDIT.

package log

import (
	"errors"
	"fmt"
	"log/slog"

	"github.com/lanrat/dns/cmd/atomdns/internal/dnslog"
)

func (l *Log) Err(err error) error { return fmt.Errorf("%s: %w", l.Key(), err) }

func (l *Log) Errf(err string) error { return fmt.Errorf("%s: %w", l.Key(), errors.New(err)) }

func Err(err error) slog.Attr { return dnslog.Error(err) }

func (l *Log) Key() string { return "log" }

var _log = func() *slog.Logger { return slog.Default().With("handler", "log") }
