// Code generated by "go run err_generate.go"; DO NOT EDIT.

package whoami

import (
	"errors"
	"fmt"
	"log/slog"

	"github.com/lanrat/dns/cmd/atomdns/internal/dnslog"
)

func (w *Whoami) Err(err error) error { return fmt.Errorf("%s: %w", w.Key(), err) }

func (w *Whoami) Errf(err string) error { return fmt.Errorf("%s: %w", w.Key(), errors.New(err)) }

func Err(err error) slog.Attr { return dnslog.Error(err) }

func (w *Whoami) Key() string { return "whoami" }

var log = func() *slog.Logger { return slog.Default().With("handler", "whoami") }
