// Code generated by "go run err_generate.go"; DO NOT EDIT.

package acl

import (
	"errors"
	"fmt"
	"log/slog"

	"github.com/lanrat/dns/cmd/atomdns/internal/dnslog"
)

func (a *Acl) Err(err error) error { return fmt.Errorf("%s: %w", a.Key(), err) }

func (a *Acl) Errf(err string) error { return fmt.Errorf("%s: %w", a.Key(), errors.New(err)) }

func Err(err error) slog.Attr { return dnslog.Error(err) }

func (a *Acl) Key() string { return "acl" }

var log = func() *slog.Logger { return slog.Default().With("handler", "acl") }
