// Code generated by "go run err_generate.go"; DO NOT EDIT.

package as112

import (
	"errors"
	"fmt"
	"log/slog"

	"github.com/lanrat/dns/cmd/atomdns/internal/dnslog"
)

func (a *As112) Err(err error) error { return fmt.Errorf("%s: %w", a.Key(), err) }

func (a *As112) Errf(err string) error { return fmt.Errorf("%s: %w", a.Key(), errors.New(err)) }

func Err(err error) slog.Attr { return dnslog.Error(err) }

func (a *As112) Key() string { return "as112" }

var log = func() *slog.Logger { return slog.Default().With("handler", "as112") }
