// Code generated by "go run err_generate.go"; DO NOT EDIT.

package any

import (
	"errors"
	"fmt"
	"log/slog"

	"github.com/lanrat/dns/cmd/atomdns/internal/dnslog"
)

func (a *Any) Err(err error) error { return fmt.Errorf("%s: %w", a.Key(), err) }

func (a *Any) Errf(err string) error { return fmt.Errorf("%s: %w", a.Key(), errors.New(err)) }

func Err(err error) slog.Attr { return dnslog.Error(err) }

func (a *Any) Key() string { return "any" }

var log = func() *slog.Logger { return slog.Default().With("handler", "any") }
