// Code generated by "go run err_generate.go"; DO NOT EDIT.

package unpack

import (
	"errors"
	"fmt"
	"log/slog"

	"github.com/lanrat/dns/cmd/atomdns/internal/dnslog"
)

func (u *Unpack) Err(err error) error { return fmt.Errorf("%s: %w", u.Key(), err) }

func (u *Unpack) Errf(err string) error { return fmt.Errorf("%s: %w", u.Key(), errors.New(err)) }

func Err(err error) slog.Attr { return dnslog.Error(err) }

func (u *Unpack) Key() string { return "unpack" }

var log = func() *slog.Logger { return slog.Default().With("handler", "unpack") }
