// Code generated by "go run err_generate.go"; DO NOT EDIT.

package dbhost

import (
	"errors"
	"fmt"
	"log/slog"

	"github.com/lanrat/dns/cmd/atomdns/internal/dnslog"
)

func (d *Dbhost) Err(err error) error { return fmt.Errorf("%s: %w", d.Key(), err) }

func (d *Dbhost) Errf(err string) error { return fmt.Errorf("%s: %w", d.Key(), errors.New(err)) }

func Err(err error) slog.Attr { return dnslog.Error(err) }

func (d *Dbhost) Key() string { return "dbhost" }

var log = func() *slog.Logger { return slog.Default().With("handler", "dbhost") }
