// Code generated by "go run err_generate.go"; DO NOT EDIT.

package drunk

import (
	"errors"
	"fmt"
	"log/slog"

	"github.com/lanrat/dns/cmd/atomdns/internal/dnslog"
)

func (d *Drunk) Err(err error) error { return fmt.Errorf("%s: %w", d.Key(), err) }

func (d *Drunk) Errf(err string) error { return fmt.Errorf("%s: %w", d.Key(), errors.New(err)) }

func Err(err error) slog.Attr { return dnslog.Error(err) }

func (d *Drunk) Key() string { return "drunk" }

var log = func() *slog.Logger { return slog.Default().With("handler", "drunk") }
