// Code generated by "go run err_generate.go"; DO NOT EDIT.

package geoip

import (
	"errors"
	"fmt"
	"log/slog"

	"github.com/lanrat/dns/cmd/atomdns/internal/dnslog"
)

func (g *Geoip) Err(err error) error { return fmt.Errorf("%s: %w", g.Key(), err) }

func (g *Geoip) Errf(err string) error { return fmt.Errorf("%s: %w", g.Key(), errors.New(err)) }

func Err(err error) slog.Attr { return dnslog.Error(err) }

func (g *Geoip) Key() string { return "geoip" }

var log = func() *slog.Logger { return slog.Default().With("handler", "geoip") }
