// Code generated by "go run err_generate.go"; DO NOT EDIT.

package random

import (
	"errors"
	"fmt"
	"log/slog"

	"github.com/lanrat/dns/cmd/atomdns/internal/dnslog"
)

func (r *Random) Err(err error) error { return fmt.Errorf("%s: %w", r.Key(), err) }

func (r *Random) Errf(err string) error { return fmt.Errorf("%s: %w", r.Key(), errors.New(err)) }

func Err(err error) slog.Attr { return dnslog.Error(err) }

func (r *Random) Key() string { return "random" }

var log = func() *slog.Logger { return slog.Default().With("handler", "random") }
