// Code generated by "go run err_generate.go"; DO NOT EDIT.

package chaos

import (
	"errors"
	"fmt"
	"log/slog"

	"github.com/lanrat/dns/cmd/atomdns/internal/dnslog"
)

func (c *Chaos) Err(err error) error { return fmt.Errorf("%s: %w", c.Key(), err) }

func (c *Chaos) Errf(err string) error { return fmt.Errorf("%s: %w", c.Key(), errors.New(err)) }

func Err(err error) slog.Attr { return dnslog.Error(err) }

func (c *Chaos) Key() string { return "chaos" }

var log = func() *slog.Logger { return slog.Default().With("handler", "chaos") }
